config/routes.rb
ProgramTci::Application.routes.draw do
  resources :programs
  root 'programs#index'
end

app/models/program.rb
class Program < ActiveRecord::Base
  validates_presence_of :title, :subtitle, :code
  validates_length_of :code, is: 6, message: "is the wrong length (should be 6 characters)"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_filter :get_program, only: [:edit, :update, :show]

  def index
    @programs = Program.all
  end

  def show
  end

  def new
    @program = Program.new
  end

  def create
    @program = Program.create(program_params)
    if @program.save
      flash[:notice] = 'Program created successfully'
      redirect_to root_path
    else
      render :new 
    end
  end

  def edit
  end

  def update
    if @program.update_attributes(program_params) #handle errors
      flash[:notice] = 'Program updated successfully'
      redirect_to @program
    else
      render :edit 
    end
  end

  def destroy
    Program.destroy(params[:id])
    flash[:notice] = 'Program destroyed'
    redirect_to root_path
  end

  private

  def program_params
    params.require(:program).permit(:title, :subtitle, :code)
  end

  def get_program
    @program = Program.find_by(id: params[:id])
    not_found unless @program
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProgramTci</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/flash'%>
<%= yield %>

</body>
</html>

app/views/programs/_program_form.html.erb
  <%= form_for @program do |f| %>
    <% if @program.errors.full_messages.present? %>
      <% @program.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    <% end %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </p>
  <p>
    <%= f.label :code %>
    <%= f.text_field :code %>
  </p>
  <%= f.submit "Submit" %>
<% end %>

app/views/programs/edit.html.erb
<h1>Update Program</h1>
<%= render 'program_form' %>

app/views/programs/index.html.erb
<div class='center-box'>
  <h1>List of All Programs</h1>
  <div id='programs'>
    <% @programs.each do |program| %>
      <h3><%= link_to program.title, program %></h3>
    <% end %>

    <%= link_to new_program_path do %>
  </div>
      <button id='create-button'>Create a new program</button>
    <% end %>
</div>

app/views/programs/new.html.erb
<div class='center-box'>
<h1>Create New Program</h1>
  <%= render 'program_form' %>
</div>

app/views/programs/show.html.erb
<div class='center-box'>
  <h1><%= @program.title %></h1>
  <h3><%= @program.subtitle %></h3>
  <p> <%= @program.code %> </p>
<%= link_to 'Edit Program', edit_program_path %><br>
<%= link_to 'Delete Program', @program, method: :delete %><br>
<%= link_to 'Return Home', root_path %>
</div>  

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class='notice'>
  <%= flash[:notice] %>
  </div>
<% end %>